SELECT ID,
       CASE
           WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
           WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
           WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
           ELSE 'LOW'
           END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC;

-- NTILE 함수를 FROM 절 안으로 옮겼을 때.
SELECT E.ID,
       CASE
           WHEN COLONY_NAME = 1 THEN 'CRITICAL'
           WHEN COLONY_NAME = 2 THEN 'HIGH'
           WHEN COLONY_NAME = 3 THEN 'MEDIUM'
           ELSE 'LOW'
           END AS COLONY_NAME
FROM (
         SELECT ID,
                NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
         FROM ECOLI_DATA
     ) AS E
ORDER BY E.ID ASC;